name: default

on:
  push:
    branches: [ default ]
  pull_request:
    branches: [ default ]

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      run: |
        git init --initial-branch=default
        git remote add origin $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
        git fetch --depth=1 --update-head-ok origin +$GITHUB_REF:default
        git checkout
    - name: toolchain
      run: rustup update stable
    - name: mdbook
      run: cargo install mdbook
    - name: version
      run: |
        rustc --version
        cargo --version
        cargo clippy --version
        cargo fmt --version
        mdbook --version
    - name: check
      run: cargo check --verbose --workspace --all-features --all-targets --release
    - name: format
      run: cargo fmt --verbose --all -- --check
    - name: clippy
      run: cargo clippy --verbose --workspace --all-features --all-targets --release -- --deny warnings
    - name: build
      run: cargo build --verbose --workspace --all-features --all-targets --release
    - name: test
      run: cargo test --verbose --workspace --all-features --all-targets --release
    - name: doc
      run: cargo doc --verbose --workspace --all-features --no-deps --release
    - name: doctest
      run: cargo test --verbose --workspace --all-features --doc
    - name: book
      run: mdbook build --dest-dir target book
    - name: booktest
      run: mdbook test --dest-dir target book
