name: default

on:
  push:
    branches: [ default ]
  pull_request:
    branches: [ default ]

jobs:
  default:
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 0
    steps:
    - name: checkout
      run: |
        git init --initial-branch=default
        git remote add origin $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
        git fetch --depth=1 --update-head-ok origin +$GITHUB_REF:default
        git checkout
    - name: rust
      run: |
        rustup update stable 
        rustup default stable
        rustup component add rustfmt
        rustup component add clippy
        rustup component add rust-docs
    - name: mdbook
      run: |
        mkdir mdbook
        curl -Lf https://github.com/rust-lang/mdBook/releases/download/v0.4.21/mdbook-v0.4.21-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        echo `pwd`/mdbook >> $GITHUB_PATH
    - name: version
      run: |
        rustc --version
        cargo --version
        cargo fmt --version
        cargo clippy --version
        mdbook --version
    - name: check
      run: cargo check --verbose --workspace --all-features --all-targets --release
    - name: format
      run: cargo fmt --verbose --all -- --check
    - name: clippy
      run: cargo clippy --verbose --workspace --all-features --all-targets --release -- --deny warnings
    - name: build
      run: cargo build --verbose --workspace --all-features --all-targets --release
    - name: test
      run: cargo test --verbose --workspace --all-features --all-targets --release
    - name: doc
      run: cargo doc --verbose --workspace --all-features --no-deps --release
    - name: doctest
      run: cargo test --verbose --workspace --all-features --doc
    - name: book
      run: mdbook build --dest-dir target book
    - name: booktest
      run: mdbook test --dest-dir target book
